[package]
name = "rust-blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10"
rand = "0.8"
hex = "0.4"
chrono = "0.4"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde-big-array = "0.3"